services:
  frontend:
    build:
      context: ./dev/frontend
      dockerfile: Dockerfile
    image: app-horadoqa-frontend:1.0.1
    ports:
      - "80:80"
  
  backend:
    build:
      context: ./dev/backend
      dockerfile: Dockerfile
    image: app-horadoqa-backend:1.0.1
    environment:
      - DATABASE_URL=postgres://horadoqa:1q2w3e4r@db:5432/horadoqa
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: horadoqa
      POSTGRES_PASSWORD: 1q2w3e4r
      POSTGRES_DB: horadoqa
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
