services:
  frontend:
    build:
      context: ./dev/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
  
  backend:
    build:
      context: ./dev/backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://horadoqa:senha@db:5432/horadoqa
    ports:
      - "5000:5000"
    depends_on:
      - db
  
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: horadoqa
      POSTGRES_PASSWORD: "senha"
      POSTGRES_DB: horadoqa
    ports:
      - "5432:5432"
