services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://horadoqa:1q2w3e4r@db:5432/horadoqa
    ports:
      - "5000:5000"
    depends_on:
      - db
  
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: horadoqa
      POSTGRES_PASSWORD: 1q2w3e4r
      POSTGRES_DB: horadoqa
    ports:
      - "5432:5432"
