version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "80"  # Expor a porta 80 internamente para o Nginx
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:senha@db:5432/meu_banco
    ports:
      - "5000:5000"
    depends_on:
      - db
  
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: meu_banco
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"   # Mapeia a porta 80 do host para o container
      - "443:443" # Mapeia a porta 443 do host para o container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Certifique-se de ter este arquivo
    depends_on:
      - frontend
