name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        run: |
          docker build -t horadoqa/dev-frontend:1.0.0 ./dev/frontend 
          docker build -t horadoqa/dev-backend:1.0.0 ./dev/backend

      - name: Push Docker images
        run: |
          docker push horadoqa/dev-frontend:1.0.0
          docker push horadoqa/dev-backend:1.0.0
